/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as marketingMarketingRouteImport } from './routes/(marketing)/_marketing'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as ApiUploadCloudflareRouteImport } from './routes/api/upload/cloudflare'
import { Route as ApiUploadBackblazeRouteImport } from './routes/api/upload/backblaze'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedAppDashboardRouteImport } from './routes/_protected/app/_dashboard'
import { Route as marketingMarketingAboutRouteRouteImport } from './routes/(marketing)/_marketing/about/route'
import { Route as marketingMarketingIndexRouteRouteImport } from './routes/(marketing)/_marketing/index/route'
import { Route as ProtectedAppDashboardVocabulariesRouteRouteImport } from './routes/_protected/app/_dashboard/vocabularies/route'
import { Route as ProtectedAppDashboardPracticesRouteRouteImport } from './routes/_protected/app/_dashboard/practices/route'
import { Route as ProtectedAppDashboardMockTestRouteRouteImport } from './routes/_protected/app/_dashboard/mock-test/route'
import { Route as ProtectedAppDashboardGrammarRouteRouteImport } from './routes/_protected/app/_dashboard/grammar/route'
import { Route as ProtectedAppDashboardIndexRouteRouteImport } from './routes/_protected/app/_dashboard/index/route'
import { Route as ProtectedAppDashboardPracticesPartChar123partChar125RouteRouteImport } from './routes/_protected/app/_dashboard/practices_/part-{$part}/route'

const ProtectedAppRouteImport = createFileRoute('/_protected/app')()

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAppRoute = ProtectedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingMarketingRoute = marketingMarketingRouteImport.update({
  id: '/(marketing)/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiUploadCloudflareRoute = ApiUploadCloudflareRouteImport.update({
  id: '/api/upload/cloudflare',
  path: '/api/upload/cloudflare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadBackblazeRoute = ApiUploadBackblazeRouteImport.update({
  id: '/api/upload/backblaze',
  path: '/api/upload/backblaze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAppDashboardRoute = ProtectedAppDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => ProtectedAppRoute,
} as any)
const marketingMarketingAboutRouteRoute =
  marketingMarketingAboutRouteRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => marketingMarketingRoute,
  } as any)
const marketingMarketingIndexRouteRoute =
  marketingMarketingIndexRouteRouteImport.update({
    id: '/',
    path: '',
    getParentRoute: () => marketingMarketingRoute,
  } as any)
const ProtectedAppDashboardVocabulariesRouteRoute =
  ProtectedAppDashboardVocabulariesRouteRouteImport.update({
    id: '/vocabularies',
    path: '/vocabularies',
    getParentRoute: () => ProtectedAppDashboardRoute,
  } as any)
const ProtectedAppDashboardPracticesRouteRoute =
  ProtectedAppDashboardPracticesRouteRouteImport.update({
    id: '/practices',
    path: '/practices',
    getParentRoute: () => ProtectedAppDashboardRoute,
  } as any)
const ProtectedAppDashboardMockTestRouteRoute =
  ProtectedAppDashboardMockTestRouteRouteImport.update({
    id: '/mock-test',
    path: '/mock-test',
    getParentRoute: () => ProtectedAppDashboardRoute,
  } as any)
const ProtectedAppDashboardGrammarRouteRoute =
  ProtectedAppDashboardGrammarRouteRouteImport.update({
    id: '/grammar',
    path: '/grammar',
    getParentRoute: () => ProtectedAppDashboardRoute,
  } as any)
const ProtectedAppDashboardIndexRouteRoute =
  ProtectedAppDashboardIndexRouteRouteImport.update({
    id: '/',
    path: '',
    getParentRoute: () => ProtectedAppDashboardRoute,
  } as any)
const ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute =
  ProtectedAppDashboardPracticesPartChar123partChar125RouteRouteImport.update({
    id: '/practices_/part-{$part}',
    path: '/practices/part-{$part}',
    getParentRoute: () => ProtectedAppDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/api/$': typeof ApiSplatRoute
  '/about': typeof marketingMarketingAboutRouteRoute
  '/app': typeof ProtectedAppDashboardIndexRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/upload/backblaze': typeof ApiUploadBackblazeRoute
  '/api/upload/cloudflare': typeof ApiUploadCloudflareRoute
  '/login': typeof AuthLoginIndexRoute
  '/app/grammar': typeof ProtectedAppDashboardGrammarRouteRoute
  '/app/mock-test': typeof ProtectedAppDashboardMockTestRouteRoute
  '/app/practices': typeof ProtectedAppDashboardPracticesRouteRoute
  '/app/vocabularies': typeof ProtectedAppDashboardVocabulariesRouteRoute
  '/app/practices/part-{$part}': typeof ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute
}
export interface FileRoutesByTo {
  '/api/$': typeof ApiSplatRoute
  '/about': typeof marketingMarketingAboutRouteRoute
  '/app': typeof ProtectedAppDashboardIndexRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/upload/backblaze': typeof ApiUploadBackblazeRoute
  '/api/upload/cloudflare': typeof ApiUploadCloudflareRoute
  '/login': typeof AuthLoginIndexRoute
  '/app/grammar': typeof ProtectedAppDashboardGrammarRouteRoute
  '/app/mock-test': typeof ProtectedAppDashboardMockTestRouteRoute
  '/app/practices': typeof ProtectedAppDashboardPracticesRouteRoute
  '/app/vocabularies': typeof ProtectedAppDashboardVocabulariesRouteRoute
  '/app/practices/part-{$part}': typeof ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/(marketing)/_marketing': typeof marketingMarketingRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/(marketing)/_marketing/': typeof marketingMarketingIndexRouteRoute
  '/(marketing)/_marketing/about': typeof marketingMarketingAboutRouteRoute
  '/_protected/app': typeof ProtectedAppRouteWithChildren
  '/_protected/app/_dashboard': typeof ProtectedAppDashboardRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/upload/backblaze': typeof ApiUploadBackblazeRoute
  '/api/upload/cloudflare': typeof ApiUploadCloudflareRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_protected/app/_dashboard/': typeof ProtectedAppDashboardIndexRouteRoute
  '/_protected/app/_dashboard/grammar': typeof ProtectedAppDashboardGrammarRouteRoute
  '/_protected/app/_dashboard/mock-test': typeof ProtectedAppDashboardMockTestRouteRoute
  '/_protected/app/_dashboard/practices': typeof ProtectedAppDashboardPracticesRouteRoute
  '/_protected/app/_dashboard/vocabularies': typeof ProtectedAppDashboardVocabulariesRouteRoute
  '/_protected/app/_dashboard/practices_/part-{$part}': typeof ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/$'
    | '/about'
    | '/app'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/upload/backblaze'
    | '/api/upload/cloudflare'
    | '/login'
    | '/app/grammar'
    | '/app/mock-test'
    | '/app/practices'
    | '/app/vocabularies'
    | '/app/practices/part-{$part}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/$'
    | '/about'
    | '/app'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/upload/backblaze'
    | '/api/upload/cloudflare'
    | '/login'
    | '/app/grammar'
    | '/app/mock-test'
    | '/app/practices'
    | '/app/vocabularies'
    | '/app/practices/part-{$part}'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/(marketing)/_marketing'
    | '/api/$'
    | '/(marketing)/_marketing/'
    | '/(marketing)/_marketing/about'
    | '/_protected/app'
    | '/_protected/app/_dashboard'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/upload/backblaze'
    | '/api/upload/cloudflare'
    | '/_auth/login/'
    | '/_protected/app/_dashboard/'
    | '/_protected/app/_dashboard/grammar'
    | '/_protected/app/_dashboard/mock-test'
    | '/_protected/app/_dashboard/practices'
    | '/_protected/app/_dashboard/vocabularies'
    | '/_protected/app/_dashboard/practices_/part-{$part}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  marketingMarketingRoute: typeof marketingMarketingRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiUploadBackblazeRoute: typeof ApiUploadBackblazeRoute
  ApiUploadCloudflareRoute: typeof ApiUploadCloudflareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/app': {
      id: '/_protected/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ProtectedAppRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/_marketing': {
      id: '/(marketing)/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/upload/cloudflare': {
      id: '/api/upload/cloudflare'
      path: '/api/upload/cloudflare'
      fullPath: '/api/upload/cloudflare'
      preLoaderRoute: typeof ApiUploadCloudflareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/backblaze': {
      id: '/api/upload/backblaze'
      path: '/api/upload/backblaze'
      fullPath: '/api/upload/backblaze'
      preLoaderRoute: typeof ApiUploadBackblazeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/app/_dashboard': {
      id: '/_protected/app/_dashboard'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ProtectedAppDashboardRouteImport
      parentRoute: typeof ProtectedAppRoute
    }
    '/(marketing)/_marketing/about': {
      id: '/(marketing)/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof marketingMarketingAboutRouteRouteImport
      parentRoute: typeof marketingMarketingRoute
    }
    '/(marketing)/_marketing/': {
      id: '/(marketing)/_marketing/'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingMarketingIndexRouteRouteImport
      parentRoute: typeof marketingMarketingRoute
    }
    '/_protected/app/_dashboard/vocabularies': {
      id: '/_protected/app/_dashboard/vocabularies'
      path: '/vocabularies'
      fullPath: '/app/vocabularies'
      preLoaderRoute: typeof ProtectedAppDashboardVocabulariesRouteRouteImport
      parentRoute: typeof ProtectedAppDashboardRoute
    }
    '/_protected/app/_dashboard/practices': {
      id: '/_protected/app/_dashboard/practices'
      path: '/practices'
      fullPath: '/app/practices'
      preLoaderRoute: typeof ProtectedAppDashboardPracticesRouteRouteImport
      parentRoute: typeof ProtectedAppDashboardRoute
    }
    '/_protected/app/_dashboard/mock-test': {
      id: '/_protected/app/_dashboard/mock-test'
      path: '/mock-test'
      fullPath: '/app/mock-test'
      preLoaderRoute: typeof ProtectedAppDashboardMockTestRouteRouteImport
      parentRoute: typeof ProtectedAppDashboardRoute
    }
    '/_protected/app/_dashboard/grammar': {
      id: '/_protected/app/_dashboard/grammar'
      path: '/grammar'
      fullPath: '/app/grammar'
      preLoaderRoute: typeof ProtectedAppDashboardGrammarRouteRouteImport
      parentRoute: typeof ProtectedAppDashboardRoute
    }
    '/_protected/app/_dashboard/': {
      id: '/_protected/app/_dashboard/'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof ProtectedAppDashboardIndexRouteRouteImport
      parentRoute: typeof ProtectedAppDashboardRoute
    }
    '/_protected/app/_dashboard/practices_/part-{$part}': {
      id: '/_protected/app/_dashboard/practices_/part-{$part}'
      path: '/practices/part-{$part}'
      fullPath: '/app/practices/part-{$part}'
      preLoaderRoute: typeof ProtectedAppDashboardPracticesPartChar123partChar125RouteRouteImport
      parentRoute: typeof ProtectedAppDashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedAppDashboardRouteChildren {
  ProtectedAppDashboardIndexRouteRoute: typeof ProtectedAppDashboardIndexRouteRoute
  ProtectedAppDashboardGrammarRouteRoute: typeof ProtectedAppDashboardGrammarRouteRoute
  ProtectedAppDashboardMockTestRouteRoute: typeof ProtectedAppDashboardMockTestRouteRoute
  ProtectedAppDashboardPracticesRouteRoute: typeof ProtectedAppDashboardPracticesRouteRoute
  ProtectedAppDashboardVocabulariesRouteRoute: typeof ProtectedAppDashboardVocabulariesRouteRoute
  ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute: typeof ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute
}

const ProtectedAppDashboardRouteChildren: ProtectedAppDashboardRouteChildren = {
  ProtectedAppDashboardIndexRouteRoute: ProtectedAppDashboardIndexRouteRoute,
  ProtectedAppDashboardGrammarRouteRoute:
    ProtectedAppDashboardGrammarRouteRoute,
  ProtectedAppDashboardMockTestRouteRoute:
    ProtectedAppDashboardMockTestRouteRoute,
  ProtectedAppDashboardPracticesRouteRoute:
    ProtectedAppDashboardPracticesRouteRoute,
  ProtectedAppDashboardVocabulariesRouteRoute:
    ProtectedAppDashboardVocabulariesRouteRoute,
  ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute:
    ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute,
}

const ProtectedAppDashboardRouteWithChildren =
  ProtectedAppDashboardRoute._addFileChildren(
    ProtectedAppDashboardRouteChildren,
  )

interface ProtectedAppRouteChildren {
  ProtectedAppDashboardRoute: typeof ProtectedAppDashboardRouteWithChildren
}

const ProtectedAppRouteChildren: ProtectedAppRouteChildren = {
  ProtectedAppDashboardRoute: ProtectedAppDashboardRouteWithChildren,
}

const ProtectedAppRouteWithChildren = ProtectedAppRoute._addFileChildren(
  ProtectedAppRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAppRoute: typeof ProtectedAppRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAppRoute: ProtectedAppRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface marketingMarketingRouteChildren {
  marketingMarketingIndexRouteRoute: typeof marketingMarketingIndexRouteRoute
  marketingMarketingAboutRouteRoute: typeof marketingMarketingAboutRouteRoute
}

const marketingMarketingRouteChildren: marketingMarketingRouteChildren = {
  marketingMarketingIndexRouteRoute: marketingMarketingIndexRouteRoute,
  marketingMarketingAboutRouteRoute: marketingMarketingAboutRouteRoute,
}

const marketingMarketingRouteWithChildren =
  marketingMarketingRoute._addFileChildren(marketingMarketingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  marketingMarketingRoute: marketingMarketingRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiUploadBackblazeRoute: ApiUploadBackblazeRoute,
  ApiUploadCloudflareRoute: ApiUploadCloudflareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
