/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OgDotpngRouteImport } from './routes/og[.]png'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProxySplatRouteImport } from './routes/proxy/$'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as marketingMarketingRouteImport } from './routes/(marketing)/_marketing'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as ApiUploadCloudflareRouteImport } from './routes/api/upload/cloudflare'
import { Route as ApiUploadBackblazeRouteImport } from './routes/api/upload/backblaze'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedAppDashboardRouteImport } from './routes/_protected/app/_dashboard'
import { Route as marketingMarketingAboutRouteRouteImport } from './routes/(marketing)/_marketing/about/route'
import { Route as marketingMarketingIndexRouteRouteImport } from './routes/(marketing)/_marketing/index/route'
import { Route as ProtectedAppDashboardVocabulariesRouteRouteImport } from './routes/_protected/app/_dashboard/vocabularies/route'
import { Route as ProtectedAppDashboardMockTestRouteRouteImport } from './routes/_protected/app/_dashboard/mock-test/route'
import { Route as ProtectedAppDashboardGrammarRouteRouteImport } from './routes/_protected/app/_dashboard/grammar/route'
import { Route as ProtectedAppDashboardIndexRouteRouteImport } from './routes/_protected/app/_dashboard/index/route'
import { Route as ProtectedAppDashboardPracticesPartChar123partChar125RouteRouteImport } from './routes/_protected/app/_dashboard/practices/part-{$part}/route'
import { Route as ProtectedAppDashboardPracticesIndexRouteRouteImport } from './routes/_protected/app/_dashboard/practices/index/route'
import { Route as ProtectedAppPracticesPracticesPartSessionIdIndexRouteRouteImport } from './routes/_protected/app/_practices/practices.$part.$session-id/index/route'
import { Route as ProtectedAppPracticesPracticesPartSessionIdResultsSummaryRouteRouteImport } from './routes/_protected/app/_practices/practices.$part.$session-id/results/summary/route'
import { Route as ProtectedAppPracticesPracticesPartSessionIdResultsIndexRouteRouteImport } from './routes/_protected/app/_practices/practices.$part.$session-id/results/index/route'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDotpngRoute = OgDotpngRouteImport.update({
  id: '/og.png',
  path: '/og.png',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxySplatRoute = ProxySplatRouteImport.update({
  id: '/proxy/$',
  path: '/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingMarketingRoute = marketingMarketingRouteImport.update({
  id: '/(marketing)/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiUploadCloudflareRoute = ApiUploadCloudflareRouteImport.update({
  id: '/api/upload/cloudflare',
  path: '/api/upload/cloudflare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadBackblazeRoute = ApiUploadBackblazeRouteImport.update({
  id: '/api/upload/backblaze',
  path: '/api/upload/backblaze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAppDashboardRoute = ProtectedAppDashboardRouteImport.update({
  id: '/app/_dashboard',
  path: '/app',
  getParentRoute: () => ProtectedRoute,
} as any)
const marketingMarketingAboutRouteRoute =
  marketingMarketingAboutRouteRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => marketingMarketingRoute,
  } as any)
const marketingMarketingIndexRouteRoute =
  marketingMarketingIndexRouteRouteImport.update({
    id: '/',
    path: '',
    getParentRoute: () => marketingMarketingRoute,
  } as any)
const ProtectedAppDashboardVocabulariesRouteRoute =
  ProtectedAppDashboardVocabulariesRouteRouteImport.update({
    id: '/vocabularies',
    path: '/vocabularies',
    getParentRoute: () => ProtectedAppDashboardRoute,
  } as any)
const ProtectedAppDashboardMockTestRouteRoute =
  ProtectedAppDashboardMockTestRouteRouteImport.update({
    id: '/mock-test',
    path: '/mock-test',
    getParentRoute: () => ProtectedAppDashboardRoute,
  } as any)
const ProtectedAppDashboardGrammarRouteRoute =
  ProtectedAppDashboardGrammarRouteRouteImport.update({
    id: '/grammar',
    path: '/grammar',
    getParentRoute: () => ProtectedAppDashboardRoute,
  } as any)
const ProtectedAppDashboardIndexRouteRoute =
  ProtectedAppDashboardIndexRouteRouteImport.update({
    id: '/',
    path: '',
    getParentRoute: () => ProtectedAppDashboardRoute,
  } as any)
const ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute =
  ProtectedAppDashboardPracticesPartChar123partChar125RouteRouteImport.update({
    id: '/practices/part-{$part}',
    path: '/practices/part-{$part}',
    getParentRoute: () => ProtectedAppDashboardRoute,
  } as any)
const ProtectedAppDashboardPracticesIndexRouteRoute =
  ProtectedAppDashboardPracticesIndexRouteRouteImport.update({
    id: '/practices/',
    path: '/practices',
    getParentRoute: () => ProtectedAppDashboardRoute,
  } as any)
const ProtectedAppPracticesPracticesPartSessionIdIndexRouteRoute =
  ProtectedAppPracticesPracticesPartSessionIdIndexRouteRouteImport.update({
    id: '/app/_practices/practices/$part/$session-id/',
    path: '/app/practices/$part/$session-id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAppPracticesPracticesPartSessionIdResultsSummaryRouteRoute =
  ProtectedAppPracticesPracticesPartSessionIdResultsSummaryRouteRouteImport.update(
    {
      id: '/app/_practices/practices/$part/$session-id/results/summary',
      path: '/app/practices/$part/$session-id/results/summary',
      getParentRoute: () => ProtectedRoute,
    } as any,
  )
const ProtectedAppPracticesPracticesPartSessionIdResultsIndexRouteRoute =
  ProtectedAppPracticesPracticesPartSessionIdResultsIndexRouteRouteImport.update(
    {
      id: '/app/_practices/practices/$part/$session-id/results/',
      path: '/app/practices/$part/$session-id/results',
      getParentRoute: () => ProtectedRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/og.png': typeof OgDotpngRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/proxy/$': typeof ProxySplatRoute
  '/about': typeof marketingMarketingAboutRouteRoute
  '/app': typeof ProtectedAppDashboardIndexRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/upload/backblaze': typeof ApiUploadBackblazeRoute
  '/api/upload/cloudflare': typeof ApiUploadCloudflareRoute
  '/login': typeof AuthLoginIndexRoute
  '/app/grammar': typeof ProtectedAppDashboardGrammarRouteRoute
  '/app/mock-test': typeof ProtectedAppDashboardMockTestRouteRoute
  '/app/vocabularies': typeof ProtectedAppDashboardVocabulariesRouteRoute
  '/app/practices': typeof ProtectedAppDashboardPracticesIndexRouteRoute
  '/app/practices/part-{$part}': typeof ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute
  '/app/practices/$part/$session-id': typeof ProtectedAppPracticesPracticesPartSessionIdIndexRouteRoute
  '/app/practices/$part/$session-id/results': typeof ProtectedAppPracticesPracticesPartSessionIdResultsIndexRouteRoute
  '/app/practices/$part/$session-id/results/summary': typeof ProtectedAppPracticesPracticesPartSessionIdResultsSummaryRouteRoute
}
export interface FileRoutesByTo {
  '/og.png': typeof OgDotpngRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/proxy/$': typeof ProxySplatRoute
  '/about': typeof marketingMarketingAboutRouteRoute
  '/app': typeof ProtectedAppDashboardIndexRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/upload/backblaze': typeof ApiUploadBackblazeRoute
  '/api/upload/cloudflare': typeof ApiUploadCloudflareRoute
  '/login': typeof AuthLoginIndexRoute
  '/app/grammar': typeof ProtectedAppDashboardGrammarRouteRoute
  '/app/mock-test': typeof ProtectedAppDashboardMockTestRouteRoute
  '/app/vocabularies': typeof ProtectedAppDashboardVocabulariesRouteRoute
  '/app/practices': typeof ProtectedAppDashboardPracticesIndexRouteRoute
  '/app/practices/part-{$part}': typeof ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute
  '/app/practices/$part/$session-id': typeof ProtectedAppPracticesPracticesPartSessionIdIndexRouteRoute
  '/app/practices/$part/$session-id/results': typeof ProtectedAppPracticesPracticesPartSessionIdResultsIndexRouteRoute
  '/app/practices/$part/$session-id/results/summary': typeof ProtectedAppPracticesPracticesPartSessionIdResultsSummaryRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/og.png': typeof OgDotpngRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(marketing)/_marketing': typeof marketingMarketingRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/proxy/$': typeof ProxySplatRoute
  '/(marketing)/_marketing/': typeof marketingMarketingIndexRouteRoute
  '/(marketing)/_marketing/about': typeof marketingMarketingAboutRouteRoute
  '/_protected/app/_dashboard': typeof ProtectedAppDashboardRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/upload/backblaze': typeof ApiUploadBackblazeRoute
  '/api/upload/cloudflare': typeof ApiUploadCloudflareRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_protected/app/_dashboard/': typeof ProtectedAppDashboardIndexRouteRoute
  '/_protected/app/_dashboard/grammar': typeof ProtectedAppDashboardGrammarRouteRoute
  '/_protected/app/_dashboard/mock-test': typeof ProtectedAppDashboardMockTestRouteRoute
  '/_protected/app/_dashboard/vocabularies': typeof ProtectedAppDashboardVocabulariesRouteRoute
  '/_protected/app/_dashboard/practices/': typeof ProtectedAppDashboardPracticesIndexRouteRoute
  '/_protected/app/_dashboard/practices/part-{$part}': typeof ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute
  '/_protected/app/_practices/practices/$part/$session-id/': typeof ProtectedAppPracticesPracticesPartSessionIdIndexRouteRoute
  '/_protected/app/_practices/practices/$part/$session-id/results/': typeof ProtectedAppPracticesPracticesPartSessionIdResultsIndexRouteRoute
  '/_protected/app/_practices/practices/$part/$session-id/results/summary': typeof ProtectedAppPracticesPracticesPartSessionIdResultsSummaryRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/og.png'
    | '/sitemap.xml'
    | '/api/$'
    | '/proxy/$'
    | '/about'
    | '/app'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/upload/backblaze'
    | '/api/upload/cloudflare'
    | '/login'
    | '/app/grammar'
    | '/app/mock-test'
    | '/app/vocabularies'
    | '/app/practices'
    | '/app/practices/part-{$part}'
    | '/app/practices/$part/$session-id'
    | '/app/practices/$part/$session-id/results'
    | '/app/practices/$part/$session-id/results/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/og.png'
    | '/sitemap.xml'
    | '/api/$'
    | '/proxy/$'
    | '/about'
    | '/app'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/upload/backblaze'
    | '/api/upload/cloudflare'
    | '/login'
    | '/app/grammar'
    | '/app/mock-test'
    | '/app/vocabularies'
    | '/app/practices'
    | '/app/practices/part-{$part}'
    | '/app/practices/$part/$session-id'
    | '/app/practices/$part/$session-id/results'
    | '/app/practices/$part/$session-id/results/summary'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/og.png'
    | '/sitemap.xml'
    | '/(marketing)/_marketing'
    | '/api/$'
    | '/proxy/$'
    | '/(marketing)/_marketing/'
    | '/(marketing)/_marketing/about'
    | '/_protected/app/_dashboard'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/upload/backblaze'
    | '/api/upload/cloudflare'
    | '/_auth/login/'
    | '/_protected/app/_dashboard/'
    | '/_protected/app/_dashboard/grammar'
    | '/_protected/app/_dashboard/mock-test'
    | '/_protected/app/_dashboard/vocabularies'
    | '/_protected/app/_dashboard/practices/'
    | '/_protected/app/_dashboard/practices/part-{$part}'
    | '/_protected/app/_practices/practices/$part/$session-id/'
    | '/_protected/app/_practices/practices/$part/$session-id/results/'
    | '/_protected/app/_practices/practices/$part/$session-id/results/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  OgDotpngRoute: typeof OgDotpngRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  marketingMarketingRoute: typeof marketingMarketingRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ProxySplatRoute: typeof ProxySplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiUploadBackblazeRoute: typeof ApiUploadBackblazeRoute
  ApiUploadCloudflareRoute: typeof ApiUploadCloudflareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og.png': {
      id: '/og.png'
      path: '/og.png'
      fullPath: '/og.png'
      preLoaderRoute: typeof OgDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxy/$': {
      id: '/proxy/$'
      path: '/proxy/$'
      fullPath: '/proxy/$'
      preLoaderRoute: typeof ProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/_marketing': {
      id: '/(marketing)/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/upload/cloudflare': {
      id: '/api/upload/cloudflare'
      path: '/api/upload/cloudflare'
      fullPath: '/api/upload/cloudflare'
      preLoaderRoute: typeof ApiUploadCloudflareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/backblaze': {
      id: '/api/upload/backblaze'
      path: '/api/upload/backblaze'
      fullPath: '/api/upload/backblaze'
      preLoaderRoute: typeof ApiUploadBackblazeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/app/_dashboard': {
      id: '/_protected/app/_dashboard'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ProtectedAppDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/(marketing)/_marketing/about': {
      id: '/(marketing)/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof marketingMarketingAboutRouteRouteImport
      parentRoute: typeof marketingMarketingRoute
    }
    '/(marketing)/_marketing/': {
      id: '/(marketing)/_marketing/'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingMarketingIndexRouteRouteImport
      parentRoute: typeof marketingMarketingRoute
    }
    '/_protected/app/_dashboard/vocabularies': {
      id: '/_protected/app/_dashboard/vocabularies'
      path: '/vocabularies'
      fullPath: '/app/vocabularies'
      preLoaderRoute: typeof ProtectedAppDashboardVocabulariesRouteRouteImport
      parentRoute: typeof ProtectedAppDashboardRoute
    }
    '/_protected/app/_dashboard/mock-test': {
      id: '/_protected/app/_dashboard/mock-test'
      path: '/mock-test'
      fullPath: '/app/mock-test'
      preLoaderRoute: typeof ProtectedAppDashboardMockTestRouteRouteImport
      parentRoute: typeof ProtectedAppDashboardRoute
    }
    '/_protected/app/_dashboard/grammar': {
      id: '/_protected/app/_dashboard/grammar'
      path: '/grammar'
      fullPath: '/app/grammar'
      preLoaderRoute: typeof ProtectedAppDashboardGrammarRouteRouteImport
      parentRoute: typeof ProtectedAppDashboardRoute
    }
    '/_protected/app/_dashboard/': {
      id: '/_protected/app/_dashboard/'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof ProtectedAppDashboardIndexRouteRouteImport
      parentRoute: typeof ProtectedAppDashboardRoute
    }
    '/_protected/app/_dashboard/practices/part-{$part}': {
      id: '/_protected/app/_dashboard/practices/part-{$part}'
      path: '/practices/part-{$part}'
      fullPath: '/app/practices/part-{$part}'
      preLoaderRoute: typeof ProtectedAppDashboardPracticesPartChar123partChar125RouteRouteImport
      parentRoute: typeof ProtectedAppDashboardRoute
    }
    '/_protected/app/_dashboard/practices/': {
      id: '/_protected/app/_dashboard/practices/'
      path: '/practices'
      fullPath: '/app/practices'
      preLoaderRoute: typeof ProtectedAppDashboardPracticesIndexRouteRouteImport
      parentRoute: typeof ProtectedAppDashboardRoute
    }
    '/_protected/app/_practices/practices/$part/$session-id/': {
      id: '/_protected/app/_practices/practices/$part/$session-id/'
      path: '/app/practices/$part/$session-id'
      fullPath: '/app/practices/$part/$session-id'
      preLoaderRoute: typeof ProtectedAppPracticesPracticesPartSessionIdIndexRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app/_practices/practices/$part/$session-id/results/summary': {
      id: '/_protected/app/_practices/practices/$part/$session-id/results/summary'
      path: '/app/practices/$part/$session-id/results/summary'
      fullPath: '/app/practices/$part/$session-id/results/summary'
      preLoaderRoute: typeof ProtectedAppPracticesPracticesPartSessionIdResultsSummaryRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app/_practices/practices/$part/$session-id/results/': {
      id: '/_protected/app/_practices/practices/$part/$session-id/results/'
      path: '/app/practices/$part/$session-id/results'
      fullPath: '/app/practices/$part/$session-id/results'
      preLoaderRoute: typeof ProtectedAppPracticesPracticesPartSessionIdResultsIndexRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedAppDashboardRouteChildren {
  ProtectedAppDashboardIndexRouteRoute: typeof ProtectedAppDashboardIndexRouteRoute
  ProtectedAppDashboardGrammarRouteRoute: typeof ProtectedAppDashboardGrammarRouteRoute
  ProtectedAppDashboardMockTestRouteRoute: typeof ProtectedAppDashboardMockTestRouteRoute
  ProtectedAppDashboardVocabulariesRouteRoute: typeof ProtectedAppDashboardVocabulariesRouteRoute
  ProtectedAppDashboardPracticesIndexRouteRoute: typeof ProtectedAppDashboardPracticesIndexRouteRoute
  ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute: typeof ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute
}

const ProtectedAppDashboardRouteChildren: ProtectedAppDashboardRouteChildren = {
  ProtectedAppDashboardIndexRouteRoute: ProtectedAppDashboardIndexRouteRoute,
  ProtectedAppDashboardGrammarRouteRoute:
    ProtectedAppDashboardGrammarRouteRoute,
  ProtectedAppDashboardMockTestRouteRoute:
    ProtectedAppDashboardMockTestRouteRoute,
  ProtectedAppDashboardVocabulariesRouteRoute:
    ProtectedAppDashboardVocabulariesRouteRoute,
  ProtectedAppDashboardPracticesIndexRouteRoute:
    ProtectedAppDashboardPracticesIndexRouteRoute,
  ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute:
    ProtectedAppDashboardPracticesPartChar123partChar125RouteRoute,
}

const ProtectedAppDashboardRouteWithChildren =
  ProtectedAppDashboardRoute._addFileChildren(
    ProtectedAppDashboardRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedAppDashboardRoute: typeof ProtectedAppDashboardRouteWithChildren
  ProtectedAppPracticesPracticesPartSessionIdIndexRouteRoute: typeof ProtectedAppPracticesPracticesPartSessionIdIndexRouteRoute
  ProtectedAppPracticesPracticesPartSessionIdResultsIndexRouteRoute: typeof ProtectedAppPracticesPracticesPartSessionIdResultsIndexRouteRoute
  ProtectedAppPracticesPracticesPartSessionIdResultsSummaryRouteRoute: typeof ProtectedAppPracticesPracticesPartSessionIdResultsSummaryRouteRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAppDashboardRoute: ProtectedAppDashboardRouteWithChildren,
  ProtectedAppPracticesPracticesPartSessionIdIndexRouteRoute:
    ProtectedAppPracticesPracticesPartSessionIdIndexRouteRoute,
  ProtectedAppPracticesPracticesPartSessionIdResultsIndexRouteRoute:
    ProtectedAppPracticesPracticesPartSessionIdResultsIndexRouteRoute,
  ProtectedAppPracticesPracticesPartSessionIdResultsSummaryRouteRoute:
    ProtectedAppPracticesPracticesPartSessionIdResultsSummaryRouteRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface marketingMarketingRouteChildren {
  marketingMarketingIndexRouteRoute: typeof marketingMarketingIndexRouteRoute
  marketingMarketingAboutRouteRoute: typeof marketingMarketingAboutRouteRoute
}

const marketingMarketingRouteChildren: marketingMarketingRouteChildren = {
  marketingMarketingIndexRouteRoute: marketingMarketingIndexRouteRoute,
  marketingMarketingAboutRouteRoute: marketingMarketingAboutRouteRoute,
}

const marketingMarketingRouteWithChildren =
  marketingMarketingRoute._addFileChildren(marketingMarketingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  OgDotpngRoute: OgDotpngRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  marketingMarketingRoute: marketingMarketingRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ProxySplatRoute: ProxySplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiUploadBackblazeRoute: ApiUploadBackblazeRoute,
  ApiUploadCloudflareRoute: ApiUploadCloudflareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
